---
- hosts: localhost
  connection: local
  
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['zabbix'] }}"

  tasks:

  - name: For each host, scan for its ssh public key
    shell: "ping -c 1 {{ item }} > /dev/null && ssh-keyscan {{ item }},`dig +short {{ item }}`"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes

  - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"
    ignore_errors: yes

- hosts: zabbix
  remote_user: root
  tasks:
    - name: create ansible user
      user:
        name: ansible
        state: present
    - name: add sudo privileges for ansible user
      lineinfile:
        path: /etc/sudoers.d/ansibleuser
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'
    - name: add trusted ssh key for ansible user
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: reboot node for applying changes
      reboot:  
...
